### ISSUE TITLE
Component analyses failure

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-server#90] opened 2017-07-21 14:57 UTC
API call:

```
curl -v -k -H "Authorization: Bearer {proper_token} localhost:32000/api/v1/component-analyses/npm/lodash/4.17.4
```

Error messages seen in the log file (I hope they are related to this issue)

```
worker-ingestion_1      | 21 14:47:02,175 [ERROR] celery.app.trace: Task selinon.SelinonTaskEnvelope[be0d5c1c-c7b2-46f5-b651-b6a59d806624] raised unexpected: HTTPError('500 Server Error: Internal Server Error for url: http://data-model-importer:9192/api/v1/ingest_to_graph',)
worker-ingestion_1      | Traceback (most recent call last):
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
worker-ingestion_1      |     R = retval = fun(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker-ingestion_1      |     return self.run(*args, **kwargs)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 170, in run
worker-ingestion_1      |     raise self.retry(max_retries=0, exc=exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 668, in retry
worker-ingestion_1      |     raise_with_context(exc)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
worker-ingestion_1      |     result = task.run(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 38, in run
worker-ingestion_1      |     result = self.execute(node_args)
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/f8a_worker/workers/graph_importer.py", line 26, in execute
worker-ingestion_1      |     response.raise_for_status()
worker-ingestion_1      |   File "/usr/lib/python3.4/site-packages/requests/models.py", line 937, in raise_for_status
worker-ingestion_1      |     raise HTTPError(http_error_msg, response=self)
worker-ingestion_1      | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://data-model-importer:9192/api/v1/ingest_to_graph
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:48]:
data-model-importer_1   | Ingesting the given list of EPVs
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | ERROR:data_importer:import_epv() failed with error: Parameter validation failed:
data-model-importer_1   | Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"
data-model-importer_1   | ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
data-model-importer_1   |   File "/src/data_importer.py", line 149, in import_epv_http
data-model-importer_1   |     ver_list_keys.extend(data_source.list_files(bucket_name=config.AWS_EPV_BUCKET, prefix=ver_key_prefix))
data-model-importer_1   |   File "/src/data_source/s3_data_source.py", line 55, in list_files
data-model-importer_1   |     for obj in bucket.objects.filter(Prefix=prefix):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
data-model-importer_1   |     for page in self.pages():
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
data-model-importer_1   |     for page in pages:
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 249, in __iter__
data-model-importer_1   |     response = self._make_request(current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 326, in _make_request
data-model-importer_1   |     return self._method(**current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
data-model-importer_1   |     return self._make_api_call(operation_name, kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 573, in _make_api_call
data-model-importer_1   |     api_params, operation_model, context=request_context)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 625, in _convert_to_request_dict
data-model-importer_1   |     params=api_params, model=operation_model, context=context)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
data-model-importer_1   |     return self._emit(event_name, kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
data-model-importer_1   |     response = handler(**kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/handlers.py", line 212, in validate_bucket_name
data-model-importer_1   |     raise ParamValidationError(report=error_msg)
data-model-importer_1   | ParamValidationError: Parameter validation failed:
data-model-importer_1   | Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255
```

OTOH the old analyses are reachable.

**Comment by miteshvp** [comment] 2017-07-21 15:49
@tisnik - this is because data-model-importer is not finding the correct bucket.
https://github.com/fabric8-analytics/fabric8-analytics-common/pull/129/ should fix the issue. Feel free to merge if you're ok

**Comment by tisnik** [comment] 2017-07-21 16:32
Thanks @miteshvp. As far as I can tell, all endpoints you changed are reachable, so 👍 on my side.

**Comment by samuzzal-choudhury** [comment] 2017-09-18 18:22
The issue is resolved. Hence, closing. @tisnik please reopen if you think otherwise.

**Closed by samuzzal-choudhury** 2017-09-18 18:22 UTC
Labels: area/analytics/core-api, stream/integration, team/analytics
